var productsBase = [
    {
        id : '001',
        name : 'MANGO PEOPLE T-SHIRT 001',
        imgS : 'img/product/product-1.jpg',
        imgL : 'img/product/product-1.jpg',
        rating : 4,
        color : 'red',
        size : 'XIi',
        price : 700.00,
    },
    {
        id : '002',
        name : 'MANGO PEOPLE T-SHIRT 002',
        imgS : 'img/product/product-3.jpg',
        imgL : 'img/product/product-3.jpg',
        rating : 3,
        color : 'green',
        size : 'M',
        price : 870.00,
    },
    {
        id : '003',
        name : 'MANGO PEOPLE T-SHIRT 003',
        imgS : 'img/product/product-10.jpg',
        imgL : 'img/product/product-10.jpg',
        rating : 1,
        color : 'blue',
        size : 'L',
        price : 1200.00,
    },
];